# Generated by Django 4.2.13 on 2024-07-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_initial_deposit_date_userbankaccount_initial_deposite_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='bankrupcy',
            field=models.BooleanField(default=False),
        ),
    ]
